version: "3"
services:
  db: #서비스명
    image: mysql:5.7
    container_name: mysql-5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/dongyulim/data/mysql:/var/lib/mysql

